#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by localhost - 2024/11/27 04:58:23
# Search URL: http://localhost:8080/esg-search/wget?project=CORDEX&variable=pr&domain=EUR-11&rcm_name=RCA4&driving_model=MPI-M-MPI-ESM-LR&ensemble=r1i1p1&experiment=rcp45&time_frequency=1hr
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://localhost:8080/esg-search/wget?project=CORDEX&variable=pr&domain=EUR-11&rcm_name=RCA4&driving_model=MPI-M-MPI-ESM-LR&ensemble=r1i1p1&experiment=rcp45&time_frequency=1hr'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_200601010030-200612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_200601010030-200612312330.nc' 'SHA256' '13a4d53965f9eb8b731827305e07cd74212500794291768c10dc9da2c3d825f2'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_200701010030-200712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_200701010030-200712312330.nc' 'SHA256' '1ebf00a44eb9955d499a135b2a58e55af635fd99856df1c2c8674dddc1b2051d'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_200801010030-200812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_200801010030-200812312330.nc' 'SHA256' '5761e302ae6a149ae8df778cb9543e63ee155d69bbbb53b81314a84869efb663'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_200901010030-200912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_200901010030-200912312330.nc' 'SHA256' 'b4ff51f1e4b59fd1a12cf13fa14d4eb055c830882ad98524383fb51f380d80cb'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201001010030-201012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201001010030-201012312330.nc' 'SHA256' '2bb655c9170c458f7d8dc9cf09d4dce78eb3ec2585c6ca96fb4e6b0bc4ffdf70'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201101010030-201112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201101010030-201112312330.nc' 'SHA256' '0f84b8a8d007656b80cb737b4c14633ba5d51e69af5ba92ca46f82f7eb52baec'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201201010030-201212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201201010030-201212312330.nc' 'SHA256' '7bf3205826b73b963722833419f29e567879cd05ccb0f1ac46a0d539146bbfb6'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201301010030-201312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201301010030-201312312330.nc' 'SHA256' '14fc04846c4511445a44bb8ba3e9735058f80c6b9474169735fc5137cc53a45e'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201401010030-201412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201401010030-201412312330.nc' 'SHA256' '99328bed448d8f81330a3a6360b0bdb8af3b29fe12dfedbdfdb68f5cdab19f41'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201501010030-201512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201501010030-201512312330.nc' 'SHA256' '148da20f66f95ad9ec278b2afa3e38db42d14a8bb55db989d04e101d54b8d255'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201601010030-201612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201601010030-201612312330.nc' 'SHA256' 'b597ee99d454e677d80bfd309aca7182b2f4829dd49b11b3a36f70c18773966f'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201701010030-201712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201701010030-201712312330.nc' 'SHA256' '453ec22daae22efbad514273220f351639c01659e09864a5022f046e20dadfa1'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201801010030-201812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201801010030-201812312330.nc' 'SHA256' '4bac8b9bb536df16cc30522b5863555392eeaee23d68599e0b477c809c15181d'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201901010030-201912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_201901010030-201912312330.nc' 'SHA256' 'e35c1d061e75eab217ec6fee6640cc15638a70a89912e16a0b13973c49b11a4a'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202001010030-202012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202001010030-202012312330.nc' 'SHA256' '2c76a98ca0332bba1fc00176b8eba2a312b30c2e21480450115ebcb24e389416'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202101010030-202112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202101010030-202112312330.nc' 'SHA256' 'b47b30d3954c4171dee803bf7914bb2b81eaa626fbafd016bea7098b5e039b05'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202201010030-202212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202201010030-202212312330.nc' 'SHA256' '22775726d33a375a8bf88fad5928db9621ecbea864223bcc8be25c0c001a1891'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202301010030-202312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202301010030-202312312330.nc' 'SHA256' '64c84e3519235bb1c437e106d66eea9946fb16fbcc12cb1eb17be2d76d5c244f'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202401010030-202412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202401010030-202412312330.nc' 'SHA256' '7c7c5f47827ed22b7491a38f2fdabfb011db69f08f513e3f1fe1345d34729f39'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202501010030-202512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202501010030-202512312330.nc' 'SHA256' '480a9f69d9dfe1a7d901476dcf3502e5fa53dd6bdbd9a7436805ee9e1185f851'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202601010030-202612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202601010030-202612312330.nc' 'SHA256' 'cecca3838993473c7ddaeeaa720f81828ab14153aab27b06fa13350e3d7c8475'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202701010030-202712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202701010030-202712312330.nc' 'SHA256' '31b37622f0876df9473d5c83c6e4f36cc4a74a28f31de599cd0b43117757d5a6'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202801010030-202812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202801010030-202812312330.nc' 'SHA256' 'a853a81ed61fe551f3a22934a08fd094c5d6be2172b1f9d85d826621d949cec4'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202901010030-202912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_202901010030-202912312330.nc' 'SHA256' 'be6250550d717d90b913afde0595ef164621342a9023e4a7ae10165c492dcd2b'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203001010030-203012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203001010030-203012312330.nc' 'SHA256' 'b414c355b808914e659079f921c6ace2497728cac80c71f60f9129ee66b48fea'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203101010030-203112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203101010030-203112312330.nc' 'SHA256' '141af26994d61b3d014a3c877b33e4b8124dc5fb3d1018c2ff904d238796d5a9'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203201010030-203212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203201010030-203212312330.nc' 'SHA256' '26a159013706a0916c16296c69a2c7664812f2fd6ab7361b37c7e96468a2b37f'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203301010030-203312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203301010030-203312312330.nc' 'SHA256' '31877f506d0f32482dc80ad4256f23d890969962b1ec70f0c05b16b97cb79804'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203401010030-203412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203401010030-203412312330.nc' 'SHA256' 'cf4e6534ec1d4bf3eeab036f5853cf7b04818268b9e8c0af1a33edb78e63d071'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203501010030-203512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203501010030-203512312330.nc' 'SHA256' '27283354af798dfdecdfcea65b65e0d5722422e3619f2f3dae0c193d0bee87af'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203601010030-203612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203601010030-203612312330.nc' 'SHA256' 'a211f5eb9a929af9fda9f30ea19759ca493216a4c90aa313f9e901a869abec0e'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203701010030-203712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203701010030-203712312330.nc' 'SHA256' '94ea4ed9488c44a4938196dc85e3a106dcd14e97da163d4b2a2cddc6f6e67967'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203801010030-203812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203801010030-203812312330.nc' 'SHA256' '292bdb1f951b849f497ec82e6f778add683c9021a21f4afaf7052d11451e8117'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203901010030-203912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_203901010030-203912312330.nc' 'SHA256' 'd0496df239b78e628741eb5465c4b0a287dca47cbec5213b3626e6bb242da337'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204001010030-204012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204001010030-204012312330.nc' 'SHA256' 'c6de868a9d86a1334d6ed340378339aaa40c4bbe2ea7892531b6e343e9c12d4a'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204101010030-204112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204101010030-204112312330.nc' 'SHA256' 'd8613db442dfb4cc3cc1eb3e9655cca61d1785f87a7128f4b99b565bf0102be1'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204201010030-204212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204201010030-204212312330.nc' 'SHA256' 'f43eb9075db9ef24a240768907b82b0f927eca45e61c56c0d19fcf65d4c54569'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204301010030-204312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204301010030-204312312330.nc' 'SHA256' 'c9db880510e971968f379a4588ba1ce1be3afffb9d7063c98168f6acd3d7ca02'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204401010030-204412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204401010030-204412312330.nc' 'SHA256' '78b5d2126e73ef832cf4a51b6747eba520a24b1d41c98e0d91668f975ac93546'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204501010030-204512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204501010030-204512312330.nc' 'SHA256' 'd3f01d9bbd17fc1b91080100be4047d621bec6a19f6e431f7348e4a411f77d17'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204601010030-204612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204601010030-204612312330.nc' 'SHA256' '5a4631aa5f287486de8fae343e6432311461903f418ec0d8fe4a9b4d14a2fa24'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204701010030-204712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204701010030-204712312330.nc' 'SHA256' '2695d773dfc79f512004d17cdcb373c4d14891d9aa5c963c3e2bfc02fac86901'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204801010030-204812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204801010030-204812312330.nc' 'SHA256' 'a890ed482f9310f59faa615d9cc6d0c87a2168971c803fd7e449580faa121f81'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204901010030-204912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_204901010030-204912312330.nc' 'SHA256' '25f02e29e4e88be0f3967f4e47345f5686310a658695ca38d9f32baeca103559'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205001010030-205012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205001010030-205012312330.nc' 'SHA256' '5731f96174e09d131f8179449ca6e2d1f1d64d049ae55f9ee2425baa39a4be36'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205101010030-205112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205101010030-205112312330.nc' 'SHA256' 'bef66d0e3f93f3b091710a1675879ac9edf9e41ad61ce1f81eb93da43f3a3147'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205201010030-205212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205201010030-205212312330.nc' 'SHA256' '2f9b9babcdaf85fbdd099924d29a596deb09b5b47e2d2c01f1d37dcb040dcadb'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205301010030-205312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205301010030-205312312330.nc' 'SHA256' 'd8688137c016773e07e96dc9c6eb576680dc33c5439f7dc624f94613c5df8e25'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205401010030-205412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205401010030-205412312330.nc' 'SHA256' '7b43654bea055395051cede96f71a72536e2a08e82bca40e0dd9e9f63976ae66'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205501010030-205512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205501010030-205512312330.nc' 'SHA256' 'f3ef26123e9e176d70b5495d0b66a828e7f7a00f96281cf55378361681420702'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205601010030-205612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205601010030-205612312330.nc' 'SHA256' '64f5cfd0df9d53772541f04dddfd85442ef7fab266617a3f5d701bfd68a03ded'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205701010030-205712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205701010030-205712312330.nc' 'SHA256' 'bc9eeab23b25aae4a88dc91db4b72cab07a14c7beafefc1407f0910b40b77cc3'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205801010030-205812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205801010030-205812312330.nc' 'SHA256' '47d37e4d40b47d6daf753e1233e6d8ba080cfa8303080de3fb42a729078c8b96'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205901010030-205912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_205901010030-205912312330.nc' 'SHA256' '7c0a409660b02721cf4878dc1da05fba65e800a1f5b39402dbaa1bffc0bb7fcd'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206001010030-206012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206001010030-206012312330.nc' 'SHA256' 'f84375ae1dd3f8e189679a8019a6bedd9facb65e466a2e98fc4d233f3de884ce'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206101010030-206112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206101010030-206112312330.nc' 'SHA256' '850457309d113bd0c0c9bd8d536292f0db3e798a2e61173a91196aaa115751e1'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206201010030-206212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206201010030-206212312330.nc' 'SHA256' '8164d7b4c6f268a56b83f188410a4eefc14977105efbe197c790f6c821d8c8dd'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206301010030-206312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206301010030-206312312330.nc' 'SHA256' '2bfc6c9fea422e9f5ca4d5ebc2dc3bbe740f12635a8198012787c52fea81468b'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206401010030-206412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206401010030-206412312330.nc' 'SHA256' 'f78a6c88e1752aed8dded289d497daf73a68ad2df9f9d8cb1b12fdd0d61fa14c'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206501010030-206512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206501010030-206512312330.nc' 'SHA256' 'adecaa45cf6076aa06521c3b4bb883c5ea5a96fe45375f16e740cdb124a797ed'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206601010030-206612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206601010030-206612312330.nc' 'SHA256' 'a24cc4f0f47b927bacb1c2a67f8e48dd0069ff0dcd354768a20a0a5fb39a438a'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206701010030-206712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206701010030-206712312330.nc' 'SHA256' '320857b2c28f5733b3d385468b2fa27eda49acb1f24eb61814d33caf5ef579e6'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206801010030-206812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206801010030-206812312330.nc' 'SHA256' 'b6de18f355a63014f41a515ea924ee26691fc5181d4cef1bc57b99fd4b40ba87'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206901010030-206912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_206901010030-206912312330.nc' 'SHA256' '3a33b0e473b6357bad62bc8cdcbb1a12dad42382b5de07ae29c2cbbe6d876846'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207001010030-207012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207001010030-207012312330.nc' 'SHA256' '71909db721784c3370101f8c9437c8756e55c402c3652c13f9130f6a1afb616a'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207101010030-207112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207101010030-207112312330.nc' 'SHA256' '50bfa6eed5f9a5e9df745f4758ff0b5d57e31bb5863b54675f9de363963f08fd'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207201010030-207212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207201010030-207212312330.nc' 'SHA256' '1c8e4945e36fcc74c8fb15b62c27b8e57b6b18ba619ffe00878f568778b78da1'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207301010030-207312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207301010030-207312312330.nc' 'SHA256' '7de5514b1d64fce63b49353f2880e14a70c8daf5d7aefae6914f90f332e83a3d'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207401010030-207412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207401010030-207412312330.nc' 'SHA256' 'ea2f184b6d97a474c9f1d2bae452d2af3f3e6e86297ad6b58d1e6a5345a90f93'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207501010030-207512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207501010030-207512312330.nc' 'SHA256' 'f09cfc1fc5ba8257440c84badaf1d576d254a6717870c2ce126ccc21813216a8'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207601010030-207612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207601010030-207612312330.nc' 'SHA256' '1b3f5e45b0b45d01db77f8759e50c6f40271480665e35fabb4d8c67652e2a827'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207701010030-207712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207701010030-207712312330.nc' 'SHA256' '8416f81cd666bafaa1b492031733c996e5c49159040d910b2a71120888e65968'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207801010030-207812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207801010030-207812312330.nc' 'SHA256' '8b465533b37e060677a7b3b5fd96ef2eca90c1b768a3028a5494c9b28aa2563e'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207901010030-207912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_207901010030-207912312330.nc' 'SHA256' '098c8d030bde4871790c411349c1d018d253a36cc51d07f45bcc71987faf6e7f'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208001010030-208012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208001010030-208012312330.nc' 'SHA256' '15882e2064ecacd8098c7ce63372ecd132b05daf51c870cb480e5bfb022f60b3'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208101010030-208112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208101010030-208112312330.nc' 'SHA256' '1f38e4a7a3d06c3273ce1bd938830b27ac9ea04a25a58d3acb0a6ccad0361840'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208201010030-208212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208201010030-208212312330.nc' 'SHA256' '5087214eeb4b5f52875179b582b7cef7b74e945c2a48b94425fe0f4268c87d37'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208301010030-208312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208301010030-208312312330.nc' 'SHA256' '3d72ec9cd4f56a0ea41dc2e7d0b966845a8e79592b060d78d3f87783fa8a7e48'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208401010030-208412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208401010030-208412312330.nc' 'SHA256' '671d9eacc27808e7df855a9de2ebc1555f7905ff2f5551f00c834b7a010b1704'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208501010030-208512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208501010030-208512312330.nc' 'SHA256' '866e99c232f7203e3e7e0b9ad8baee4ec56e96e5bbaa9445420314af1b2b9179'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208601010030-208612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208601010030-208612312330.nc' 'SHA256' '49c0512cfdad14e1198e94aa144589df0d7d59b8e98506d6b80c60e8b3dcdd5a'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208701010030-208712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208701010030-208712312330.nc' 'SHA256' '303ed607dd3fea7ae0bcaf5366dce756f0a60d16cc2199b4e15a0a6613e1f67f'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208801010030-208812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208801010030-208812312330.nc' 'SHA256' '15c9abed46980daca32fafb12ebaa9f91995cda9f8e9fb18e1bceeae7ecb0711'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208901010030-208912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_208901010030-208912312330.nc' 'SHA256' 'df06f780e921dd3407071c09d201270584f58ab1c17d62c045d80bda6affbace'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209001010030-209012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209001010030-209012312330.nc' 'SHA256' 'b7bd273df3747c68616778e9d1e5e67e55e1db2b4e55e3ad53078109731149c4'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209101010030-209112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209101010030-209112312330.nc' 'SHA256' 'c7ab5de865759fb16d2e0e053243866307d9c4518a403f1232ccdb1bf94e7498'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209201010030-209212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209201010030-209212312330.nc' 'SHA256' '6b3fa7f3af7ea26d87f6adbc26df8e8eb3666b1232162bb13cc83c643c940f2d'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209301010030-209312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209301010030-209312312330.nc' 'SHA256' 'a685fcce657dc8cb209c4ebf1dff8df1b2f02057cc8c843354f766e09023d195'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209401010030-209412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209401010030-209412312330.nc' 'SHA256' '0cafde88bdc3f1b9130a829ebc9945866fff08c3ba9716fade4d7cbf50364388'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209501010030-209512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209501010030-209512312330.nc' 'SHA256' 'b64b1108b34b6189dff60c15ab20cb0bfbf611d2d596bd871d0edb954145180f'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209601010030-209612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209601010030-209612312330.nc' 'SHA256' 'b84e3a93025012f5ebbb681b88e0ab603ce7d947a3e4931fe5367311da650d53'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209701010030-209712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209701010030-209712312330.nc' 'SHA256' '51f1a1a7b768839f5e78158d1e1361aa0497b3efabef82d1ddcd27b4adc0af7a'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209801010030-209812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209801010030-209812312330.nc' 'SHA256' '81971c0b91b7acb4f8e6cdf96bcd0b67b6a6289fc7712e12007389e013332af9'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209901010030-209912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_209901010030-209912312330.nc' 'SHA256' '63f218b4b91f1d761cd297f0f4f288412119a3b7b071e2497a58419278b85053'
'pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_210001010030-210012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/MPI-M-MPI-ESM-LR/rcp45/r1i1p1/SMHI-RCA4/v1a/1hr/pr/v20191201/pr_EUR-11_MPI-M-MPI-ESM-LR_rcp45_r1i1p1_SMHI-RCA4_v1a_1hr_210001010030-210012312330.nc' 'SHA256' '8732904afd2c1aa07c2b7689d5c0da0a856f9711ea9e15fd9c4b4630b528e981'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 95 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
