#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2024/05/22 09:39:56
# Search URL: https://esgf-node.llnl.gov/esg-search/wget?project=CORDEX&variable=pr&domain=EUR-11&rcm_name=RCA4&driving_model=NCC-NorESM1-M&ensemble=r1i1p1&experiment=rcp26&time_frequency=1hr
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.llnl.gov/esg-search/wget?project=CORDEX&variable=pr&domain=EUR-11&rcm_name=RCA4&driving_model=NCC-NorESM1-M&ensemble=r1i1p1&experiment=rcp26&time_frequency=1hr'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_200601010030-200612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_200601010030-200612312330.nc' 'SHA256' '9176e386669978573c3a69a6eb0a9a5182a5505345ec0b50cbbebbf3b01f9956'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_200701010030-200712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_200701010030-200712312330.nc' 'SHA256' '09b714c8b24cc61d177a92a3b550402561769cb8ac6fe453e30ccaac0325e6f9'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_200801010030-200812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_200801010030-200812312330.nc' 'SHA256' 'ed1a10a8bbdbdb41c7dc9d598902d900cba15f51814b1910ba3bff8cd778d10b'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_200901010030-200912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_200901010030-200912312330.nc' 'SHA256' 'a3b6a288ddc4e59ad98593da68d189160e3dc2bb4c43008953a9b3c5f593b42f'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201001010030-201012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201001010030-201012312330.nc' 'SHA256' '78cf1bf9430c6b64dd0047c9575c6fddefbde1a6f65edbd7cb374c91c6432332'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201101010030-201112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201101010030-201112312330.nc' 'SHA256' '0eb50b034e402e0ef5aacffb74f7295b641d1e2a98f3be2eeb5ecea0cbc8f430'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201201010030-201212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201201010030-201212312330.nc' 'SHA256' 'e661235d8fabdf9a2c7825999f85401395475ee9aa45d7c8ba6e60081412717c'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201301010030-201312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201301010030-201312312330.nc' 'SHA256' '1fedba1ee122beb7d18bc6be807ade0c3efc6f198241584e20671ae3c03e6a61'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201401010030-201412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201401010030-201412312330.nc' 'SHA256' '006861c1b5249926f5cc73edb78f6d37d4b1d202abf1ea559c22e51be8c1eca1'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201501010030-201512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201501010030-201512312330.nc' 'SHA256' 'b4481b8b57adf9d15a4339db2c35268322db3ae2d0145afc989bf85123256b8d'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201601010030-201612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201601010030-201612312330.nc' 'SHA256' '86c78f9017a3b64e4add1e96937e3a549a129cb4278929cd606b948949570f24'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201701010030-201712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201701010030-201712312330.nc' 'SHA256' '754c8af2264cab61ce664cfc18b1fea225a2bfe522dff0d81297f0966bfd66e3'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201801010030-201812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201801010030-201812312330.nc' 'SHA256' '3ceec71106aabce28e43e257ca0b75486ebfbe650a8f5910db7b9be71db418cf'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201901010030-201912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_201901010030-201912312330.nc' 'SHA256' '70e941fa28c1399f69cc1f0153cd241c612f3d5e50cc9c49f07820eb80b7a5df'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202001010030-202012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202001010030-202012312330.nc' 'SHA256' '5d4c86524136dcae54410ed92fb72d1317ef3786b958a58de490b9151987e83d'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202101010030-202112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202101010030-202112312330.nc' 'SHA256' '49811fe42dc74c58f2c8a62e8ab1421b99c793b9c723155877dd2f0ce145cc54'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202201010030-202212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202201010030-202212312330.nc' 'SHA256' '9475ade0711095d515e5785396fa4d1a6e079db832104bad72b56f62584dae4b'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202301010030-202312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202301010030-202312312330.nc' 'SHA256' 'fdbb60c55a1615e1943659cb94ffd05cf82f9ea2e53d9831430266331c094e19'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202401010030-202412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202401010030-202412312330.nc' 'SHA256' 'e1d23f0e8caecf780c78e97b0259a3e506355d8bdd7708e7751c8691afe14717'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202501010030-202512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202501010030-202512312330.nc' 'SHA256' 'c98701cb3457a8896c4c980b9dad4416d33d38ccac005798fda020f14ece024e'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202601010030-202612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202601010030-202612312330.nc' 'SHA256' '6d03b42db8719c5467d402ffb63ef3b14aa469bf72cc7590bb548c833abc2a75'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202701010030-202712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202701010030-202712312330.nc' 'SHA256' '739988ea9e36646f7b91a52f48489bd82a0484bee319722c9680f05d4eb44ce7'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202801010030-202812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202801010030-202812312330.nc' 'SHA256' '5da05e5d6f0cf31f99010f8ea7b776adabdf823e77a3e8360ee6d966215626f6'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202901010030-202912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_202901010030-202912312330.nc' 'SHA256' '37b974584689fa802309881131a8253800c17cf0500bf052f278ea9528bf6f36'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203001010030-203012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203001010030-203012312330.nc' 'SHA256' '22d78b395841e916e0a0b6f51dc58ebe006914f844f610804b3b228498a8e2a2'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203101010030-203112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203101010030-203112312330.nc' 'SHA256' 'f2729ddb9a178c7d0522c3137bd699dfc8bc3e941cf98b4383f1747b947f5652'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203201010030-203212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203201010030-203212312330.nc' 'SHA256' 'aed764c3ed23c7fc6f3feaf4767be7a45d44ec337736f375e36101d08cc01e73'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203301010030-203312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203301010030-203312312330.nc' 'SHA256' 'a8ab8cec3a873b0f132a2210b71680f57f5c2ef54f2c7c18cbab07ecd35a4e08'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203401010030-203412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203401010030-203412312330.nc' 'SHA256' '00e068f89588b37532206a63d578646b6a36030c4f96a30537ff515f7f50517f'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203501010030-203512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203501010030-203512312330.nc' 'SHA256' '5317b47a13f1386e425c72827c5e66a7b18362b031111b3cb85326638053b64a'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203601010030-203612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203601010030-203612312330.nc' 'SHA256' 'a3c24ffdaccae189417f2f89f2ac0f7927a9f900a5eef8326c6dc1216549ea38'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203701010030-203712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203701010030-203712312330.nc' 'SHA256' '2b008ca0c0da5577eaf3443956fc91478a4019c4ad83273681cd043b50a8f623'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203801010030-203812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203801010030-203812312330.nc' 'SHA256' 'bb90c4474a46bb549a7bdfba85149c6c5e1b1073ee351cccaf254c1b9f451150'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203901010030-203912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_203901010030-203912312330.nc' 'SHA256' '41aabe62dfc1b9bca006f246366c92bcb5e6aa372ebb0b55725a98b53127c0a9'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204001010030-204012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204001010030-204012312330.nc' 'SHA256' '23d0a61dbc8acfdf4f2fe1033d68de76ccf15db905af78aed59ae79f938f84f1'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204101010030-204112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204101010030-204112312330.nc' 'SHA256' 'bff8152946f2b069f3cccfb4d8d70d59cccd403236515cd24940a7d3ebb6677f'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204201010030-204212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204201010030-204212312330.nc' 'SHA256' '92fbbeb3f9e89ae0e58a95e580f69070915873699076f8cc2754d23d80dd6a42'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204301010030-204312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204301010030-204312312330.nc' 'SHA256' 'dd132c9e331a8be068cea007330a8890ca36f2520681aabc98b6608a61bed5de'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204401010030-204412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204401010030-204412312330.nc' 'SHA256' 'f6d4a015c4862551cc9ff7b38be87afaa1d6b32baac980e6f472c799114eeb9f'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204501010030-204512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204501010030-204512312330.nc' 'SHA256' '8dd9587208fe01a78e2a35d39c1bbaaa2752fcc510cf590a9698d5d3acf75a70'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204601010030-204612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204601010030-204612312330.nc' 'SHA256' '6cca7e292a5d7c5fdfd6382f5335c0bce9875d8e364d5f8f95ec91fe445ccc0a'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204701010030-204712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204701010030-204712312330.nc' 'SHA256' '96b0f9e6e6cc6ec9b94966c6054c341191142e1457a6818b3c5effbf9e9ab59f'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204801010030-204812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204801010030-204812312330.nc' 'SHA256' '0ae14c7fdb43d51b10c7ab84b76f14885c03fe658e5782e478a2974564dcb45c'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204901010030-204912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_204901010030-204912312330.nc' 'SHA256' '3e16f5f7859288b0a18b1f32cd8f6c3253aada0177455e935a433fb1bf9c4a08'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205001010030-205012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205001010030-205012312330.nc' 'SHA256' 'fb24fb7cd1112b3c546eed71a54988933303d147ea836675a4ea595410bdd7e2'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205101010030-205112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205101010030-205112312330.nc' 'SHA256' '0ea3b4ca13f680829652c793d8f211d78b91cdba3d0f635f25a409f2fcee091d'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205201010030-205212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205201010030-205212312330.nc' 'SHA256' 'fa10e4d2992c03569ac42acfd75a466f1fe335ebf3fd2b1305302417ef8aa624'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205301010030-205312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205301010030-205312312330.nc' 'SHA256' 'cd09a7088da34b23b258d3daf999238527c14b9acc3676d3ef1075d1ab4e445c'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205401010030-205412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205401010030-205412312330.nc' 'SHA256' 'b833394c904c705cf56de4262237a6defcff803b27cc4a9340dc196800695063'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205501010030-205512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205501010030-205512312330.nc' 'SHA256' 'b44fde26b1e92a470edf833060b2dc0361541bc660ebdc07109175d4cf579b71'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205601010030-205612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205601010030-205612312330.nc' 'SHA256' '61b84f84812b727fd09f8436f2365b1b9b3b4130a1323a2e32984e0ac6519943'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205701010030-205712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205701010030-205712312330.nc' 'SHA256' 'f57541a5e38c8aaade3c33adfc5846e90242ceddb001bbc9cf3d354b9000de4b'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205801010030-205812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205801010030-205812312330.nc' 'SHA256' 'c7f59515aa1bb68261170f7f376f744a44807668a4d9e3c6891d474c9b2011d1'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205901010030-205912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_205901010030-205912312330.nc' 'SHA256' '736503e0ac7de07ffcd63d809b7c625bde7ba52686c6ee8a7e01f04eae8b304f'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206001010030-206012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206001010030-206012312330.nc' 'SHA256' '57a481412593b76d2524f7038ab78c05db257265806d4d1c174505a09e579ec6'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206101010030-206112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206101010030-206112312330.nc' 'SHA256' 'a5fcce89173c24a92bdd9e3a0d55f3b6c04b45dbd0bd5aacfd36982fcee34082'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206201010030-206212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206201010030-206212312330.nc' 'SHA256' '6f98d63cdf9656bd6b932b9218bda582fff73dae809bba166e84d7ee61ccb760'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206301010030-206312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206301010030-206312312330.nc' 'SHA256' 'd8c20a2fee63f4e5e88572cf61b4c777b14c67f9263383d4eb9c406db56ce057'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206401010030-206412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206401010030-206412312330.nc' 'SHA256' 'ed274d4ed7b49a1d8801322a7bef9528fa7f67c5d42d21c85a07c5f84e035a10'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206501010030-206512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206501010030-206512312330.nc' 'SHA256' 'a7a33a838515710edf77af7a39c803c77db76c3cbd9df3ca467c14a235bb2890'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206601010030-206612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206601010030-206612312330.nc' 'SHA256' 'e9416a53da12555cdcbe17889c502bcbeba50d857eddfe6d70b154c54d5e3d90'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206701010030-206712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206701010030-206712312330.nc' 'SHA256' 'db8b5f1793c6acd3989a998ed2dff18dfb31f14aadedc90763eff93dc17c36a1'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206801010030-206812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206801010030-206812312330.nc' 'SHA256' 'caefb4921ec5404c00f986b715e5487a65616d9a130e7cd7e9ae13fb92d598fb'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206901010030-206912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_206901010030-206912312330.nc' 'SHA256' '6fb6d73086613d9dbe03937978e4d465a71f5690ac8de9ad5a324553e9785d6a'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207001010030-207012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207001010030-207012312330.nc' 'SHA256' 'f7db594173e5351f5c99f80c6d0830a2565ff8663fcb092622d34ddc64a31073'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207101010030-207112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207101010030-207112312330.nc' 'SHA256' '128cf19fe11d629ff13e25daec774ed1f8dffbff8c1381dba604069c41fafed1'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207201010030-207212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207201010030-207212312330.nc' 'SHA256' '81f2c4c232e1bf6c8dd5b964ca8de08e6d1f0b9aa5f035cc06b600d79b0e7c58'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207301010030-207312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207301010030-207312312330.nc' 'SHA256' '63b6e2a78e75077c06e32957fbf63e0d116525e8ef087c9f9ffcdd5217bb6ea0'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207401010030-207412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207401010030-207412312330.nc' 'SHA256' '1317c8642ad9dc40d0a5b1c0205754f60562c305f9a332d1b21f0666c1a9e568'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207501010030-207512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207501010030-207512312330.nc' 'SHA256' '9a5f2fdcb3704d334d1955720813d34d8d6136fc764f32ac1bc5cd12ea3daea3'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207601010030-207612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207601010030-207612312330.nc' 'SHA256' '44109dc000ed2c6c3cd3830f087c259335e3c2ae4135255a411f603a7c8cd56f'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207701010030-207712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207701010030-207712312330.nc' 'SHA256' '1a0269f41504f9340cb1624a40a835b151d88547078e687febc27c5e1d042635'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207801010030-207812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207801010030-207812312330.nc' 'SHA256' 'cd6b2ce078b4cc9b8eb205ddf63f59a21ba96428a6ab2e1a9727114c3b5cb06f'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207901010030-207912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_207901010030-207912312330.nc' 'SHA256' 'aff60f282404ad27f3368a463079c8c2817e5be20404ced4695c8447f3a52bf8'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208001010030-208012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208001010030-208012312330.nc' 'SHA256' 'e07effdf8a6b1d9b5243620f1c851f19e1442cfa049936f532ee64e4f9b66982'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208101010030-208112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208101010030-208112312330.nc' 'SHA256' 'b6d1b6afa1a6ad3219a4f7299122c6269d792d666a90bf18af84ab2c6acf1cac'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208201010030-208212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208201010030-208212312330.nc' 'SHA256' '1a4dc37edf44544f6dddcf672bd1af60ce3e7d81f16f3de7fb3e84124bb4c28b'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208301010030-208312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208301010030-208312312330.nc' 'SHA256' '7a43b3e5b8a73310b5ceff670e726598ed5072da9a48e16fd61d4dfb3b15ee0e'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208401010030-208412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208401010030-208412312330.nc' 'SHA256' '237e813fa7b37bf1d40ef499f7a7914b3734093bfd6125ab8b9f288cfd8a0acc'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208501010030-208512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208501010030-208512312330.nc' 'SHA256' '854d10665899d1534dca763f7978abc258e2e3ecee323f39b4b7683f6172d8b4'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208601010030-208612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208601010030-208612312330.nc' 'SHA256' '81e9faffd7bd687f08b522203bda3c9813fd514aa0d8f75eb655709b7222335b'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208701010030-208712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208701010030-208712312330.nc' 'SHA256' '650b05bd40a319c57a53074ccbc9f59aa52033b6c0e71da777994b8724cad05b'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208801010030-208812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208801010030-208812312330.nc' 'SHA256' 'cc165d68ca0108945bddf9e1b638987430ae85aa93e3fe3b8da91b45558d70a5'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208901010030-208912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_208901010030-208912312330.nc' 'SHA256' '5d1f5cb89c80b1c825f36466739f186c9bb266ff261c4736776a91ba93e151b6'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209001010030-209012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209001010030-209012312330.nc' 'SHA256' '586392b3e6b8a276233117ba0d795612f708af5b6f00db6fb3c6960d1227a1fe'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209101010030-209112312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209101010030-209112312330.nc' 'SHA256' '98e35b15d65538eeda19199958d062637b646fa4a25ddb5eeda073a41282a203'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209201010030-209212312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209201010030-209212312330.nc' 'SHA256' 'dd9ba04990564074240dc8623e5cb40a0a1e0fa36e402b96e0d0ca26398cc897'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209301010030-209312312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209301010030-209312312330.nc' 'SHA256' 'dcd7e9f9617a0a71ab4ccc61e436b9f585a5e9df355dbec3f7c1d821b7f936b2'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209401010030-209412312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209401010030-209412312330.nc' 'SHA256' 'b1aabb6a9d5212e8a85b57783052f0dbbf8ad72a96dd56d3348e8094dda0e9b4'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209501010030-209512312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209501010030-209512312330.nc' 'SHA256' 'bd0601ae4d8fb89f81d7c00a0f72a6dce46730731a169987a8e3a3daaf0d1cd1'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209601010030-209612312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209601010030-209612312330.nc' 'SHA256' 'a2b4e508294b800590d3df30bea28ebe150bb533d00f54861549d203f44ae85d'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209701010030-209712312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209701010030-209712312330.nc' 'SHA256' '28dfbf8752234b25449d50c84541e8e11e1684c3a298a75e750c5c9d4a204a79'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209801010030-209812312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209801010030-209812312330.nc' 'SHA256' '53b37e4f105bba38e9b391d34fe8a5c62318e0d3ee78ee8234f98663a11f6ca3'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209901010030-209912312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_209901010030-209912312330.nc' 'SHA256' '34ca40df9c4c0a7816af1323a8809afffa1087d0fa59aa6f960625855aa9b5a6'
'pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_210001010030-210012312330.nc' 'http://esg-dn1.nsc.liu.se/thredds/fileServer/esg_dataroot7/cordexdata/cordex/output/EUR-11/SMHI/NCC-NorESM1-M/rcp26/r1i1p1/SMHI-RCA4/v1/1hr/pr/v20191201/pr_EUR-11_NCC-NorESM1-M_rcp26_r1i1p1_SMHI-RCA4_v1_1hr_210001010030-210012312330.nc' 'SHA256' '5c1ad0e76dbcb6ef4bb50ac551556c2e5c40ced704feba94ac9d7f4558ab1e07'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 95 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
