#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2024/05/22 11:26:42
# Search URL: https://esgf-node.llnl.gov/esg-search/wget?project=CORDEX&variable=tas&domain=EUR-11&rcm_name=COSMO-crCLIM-v1-1&driving_model=NCC-NorESM1-M&ensemble=r1i1p1&experiment=rcp85&time_frequency=1hr
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.llnl.gov/esg-search/wget?project=CORDEX&variable=tas&domain=EUR-11&rcm_name=COSMO-crCLIM-v1-1&driving_model=NCC-NorESM1-M&ensemble=r1i1p1&experiment=rcp85&time_frequency=1hr'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_200601010000-200612312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_200601010000-200612312300.nc' 'SHA256' 'a15d319531c9d9d587c13df1c38b6156fcce21fb49b1acbaba96074865f1fa81'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_200701010000-200712312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_200701010000-200712312300.nc' 'SHA256' 'c0feb466541f5673d8c6e72a54708ededbd479e884f3093741ca7068c8229dfc'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_200801010000-200812312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_200801010000-200812312300.nc' 'SHA256' '91805b2e9001e6185045486771c80963bbfb33f5c2480bc2cb1bc0349ee84ddc'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_200901010000-200912312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_200901010000-200912312300.nc' 'SHA256' '6eb56ecb64cd9e031f435e7734dca982103551041e2227eee21e2687415583eb'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201001010000-201012312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201001010000-201012312300.nc' 'SHA256' '97b4a5b09171fdd4ff3a680dc5f75f0f46d1cd8cd88ba879745bcf6c8833310f'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201101010000-201112312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201101010000-201112312300.nc' 'SHA256' 'dd6a491c55ea9fdf22c601e50e100a90b42bafc2bdc91460620097c3ae3fbc2f'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201201010000-201212312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201201010000-201212312300.nc' 'SHA256' '0f7b959b4a844b04e2b98fa4dad8364f79965cb58c6437c264b2bb5e0060a245'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201301010000-201312312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201301010000-201312312300.nc' 'SHA256' 'b289b4fcb8016e61e52c185f1e6be70aedeaa53daf6ed5f68d4de24b6f527d7d'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201401010000-201412312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201401010000-201412312300.nc' 'SHA256' 'a351c1a1eee1edf1c2a638fbe085c2cbf4c8017813f1cad16054a0b5028398b9'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201501010000-201512312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201501010000-201512312300.nc' 'SHA256' 'a88ea6918c088ff08b48dd2a4215088e2e27c95f3c77dec714a91b3431763c2f'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201601010000-201612312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201601010000-201612312300.nc' 'SHA256' '0ca6aa2f71cb7f4ca63cf0ef9b68cec9a31607fc8df8ea1ee52c9ffdcd3215c7'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201701010000-201712312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201701010000-201712312300.nc' 'SHA256' 'e126053c5f2c0529085ae0581007061de73a747ca39135ffc50bca1f5d3ed12e'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201801010000-201812312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201801010000-201812312300.nc' 'SHA256' '17d7c4c5cbeb47b13f33ad8868290ec49dcf94588d1d5ade9d38ab44a007bcbc'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201901010000-201912312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_201901010000-201912312300.nc' 'SHA256' '48da49dec6f20f563f7f734386f00c39bc7a27245396f79ce8e5f14a7f2248c5'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202001010000-202012312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202001010000-202012312300.nc' 'SHA256' '9759fc885f2d6046e2ad181f12dd41c645f1e1db2ad790e81cf9ad6d64d05630'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202101010000-202112312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202101010000-202112312300.nc' 'SHA256' '31aa5f35ddef706b89f70a4dbc8505be345aca358f4d8a277121adf286a64b03'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202201010000-202212312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202201010000-202212312300.nc' 'SHA256' '438669739844a6eed5a2240d1fe22dfcf9fef7669e98a52df87025b3e475eb70'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202301010000-202312312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202301010000-202312312300.nc' 'SHA256' '350be65de93506819582d1561cb7df1bcf4a093d65b640d059324ba105de3b8a'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202401010000-202412312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202401010000-202412312300.nc' 'SHA256' 'fb1cc71511bb89f5733836a5f59ab905df66e5d0347770961c15cd82e692a3b8'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202501010000-202512312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202501010000-202512312300.nc' 'SHA256' 'a8e4a9ddab124712e51e83af169f340cb306ab6f93a6eb7155ec6ac92df2767f'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202601010000-202612312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202601010000-202612312300.nc' 'SHA256' 'ac837abac6dbb01ec87a582c502b9996b81ae6201f915125db082ebd0ad45839'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202701010000-202712312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202701010000-202712312300.nc' 'SHA256' 'c231a2507eb05415445940064518dbb073412713839e21057ec98117b064d3e3'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202801010000-202812312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202801010000-202812312300.nc' 'SHA256' '536d234b802c9b10ff7534797fc48f6d3ea704ff319e6e37ceecaa3dfae3f2f0'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202901010000-202912312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_202901010000-202912312300.nc' 'SHA256' '6eb075724434d9ef8d579c2b2494e976a4701cb6ab07dd2cb75b9d1291a91a6d'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203001010000-203012312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203001010000-203012312300.nc' 'SHA256' 'e566fee7c331d82a185d3948f1ba6318e23f7067379cf84f41f098fb0ff5fb72'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203101010000-203112312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203101010000-203112312300.nc' 'SHA256' 'c09a3e96b26491a39e4c2abdad4398a6a851d3190ccffbf9a739e8bd062f10c3'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203201010000-203212312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203201010000-203212312300.nc' 'SHA256' '708e054309943766aafb599c652c4fca3f544555f246ce2908a175408af8419a'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203301010000-203312312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203301010000-203312312300.nc' 'SHA256' '77aa8176f4e221877f58844a6c1bdba60849bace054c01e901e4ef38f4232026'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203401010000-203412312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203401010000-203412312300.nc' 'SHA256' '63cc76bd90f44c8ab482304ef51c82e0d0818819b03e185f73bd637156233abf'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203501010000-203512312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203501010000-203512312300.nc' 'SHA256' '9b5fd04a9e058a8795ea00680f75e4fa406e6612814e2be9c2f5045c5ec21a32'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203601010000-203612312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203601010000-203612312300.nc' 'SHA256' '0625037e2140c5fae71bf1454749c3c8e835044a389a5dce18f6d6348d5515de'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203701010000-203712312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203701010000-203712312300.nc' 'SHA256' '9344f3c3c817f8a1b3971e019df18a11238b2cbee5e0b7efdd18048e6917e195'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203801010000-203812312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203801010000-203812312300.nc' 'SHA256' 'a0e92594484bdf596856ebc73324aab419cc3ec995772188e36b48e37bdb9904'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203901010000-203912312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_203901010000-203912312300.nc' 'SHA256' 'cf6f1871018a8b5c4c8d95076313259bd997fdee01d7bbabaefcfff2b74fa2e9'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204001010000-204012312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204001010000-204012312300.nc' 'SHA256' 'fdcce07b075959c7d8899737e87a032336aff2473ce9707d78383a88216e39b5'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204101010000-204112312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204101010000-204112312300.nc' 'SHA256' '32f539b7f7d57ecb83ec1a856c7480740d7fdc28270099e261b229be708a4cd2'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204201010000-204212312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204201010000-204212312300.nc' 'SHA256' '0e50ac3fe82c332e9fe97a0ea5a5293da5f27c18d111dd21debb8a73014d5c4a'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204301010000-204312312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204301010000-204312312300.nc' 'SHA256' 'bf065f8d3c62557a1700f94e56fe0b06c9ddb6f8b41f4a77a0b42e21e12c30ff'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204401010000-204412312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204401010000-204412312300.nc' 'SHA256' '5fd966ee2b238b348043cf9d1388186ed01a74d87b56b70f07149f968e2d1312'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204501010000-204512312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204501010000-204512312300.nc' 'SHA256' '485acfd88fa413acc9b4de31ea690a8017c4aa11617d2b7f60edd0bf8783ed63'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204601010000-204612312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204601010000-204612312300.nc' 'SHA256' '883989fede40fe7cc89a1172f4292b758fa2ee30db16abf9f223b333eff26e2e'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204701010000-204712312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204701010000-204712312300.nc' 'SHA256' 'a5903dfe9093fe5d29d855ec841cfff51d284f4e817c854668a550ce7730a2c0'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204801010000-204812312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204801010000-204812312300.nc' 'SHA256' '7a3798baa62eb54eec26575c2d968fae3a1b48fe68500e61bd5d9fa66b0fc3c2'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204901010000-204912312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_204901010000-204912312300.nc' 'SHA256' '0f4a046342b2cd7aceaba3f9c8212e64c92d542edb13f3f5d6396a5d2d67a223'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205001010000-205012312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205001010000-205012312300.nc' 'SHA256' '8170a7bd3186c04d3ec73be42a43578d418ec081995051aa6657df748db125d2'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205101010000-205112312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205101010000-205112312300.nc' 'SHA256' 'cd8b75859780b8f831bf08e35c6e421565a857827b0d3b2634b9557e4ef90c89'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205201010000-205212312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205201010000-205212312300.nc' 'SHA256' '745b737f511a874d1311a57ff738229d9995fb074fc0aee15476cbbf2500755a'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205301010000-205312312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205301010000-205312312300.nc' 'SHA256' '324526c55f6848bf7b4f780bbe32d8a7b96945acab7dffd7fea78b571276d9f4'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205401010000-205412312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205401010000-205412312300.nc' 'SHA256' 'c3e2115ba0f8adbe426386ef545016b31790c2e3917da97f332c3cc27a0c28a3'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205501010000-205512312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205501010000-205512312300.nc' 'SHA256' '1e42975fec7d93d4e781915693766ee1d295a535af787d444ed0d320f348aa5b'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205601010000-205612312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205601010000-205612312300.nc' 'SHA256' '7032bfd0066726a5798fdc2cbfea6b586784e48a1ee7f6e9c57f604e1f726435'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205701010000-205712312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205701010000-205712312300.nc' 'SHA256' '1a83fa04de95f2d450067e17bfb9b3eba8038767d06daeef5bd407cbb61add8d'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205801010000-205812312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205801010000-205812312300.nc' 'SHA256' 'c4846c859e59d6fab66fa6e1b1eb63299245af48461708d7c0d6253ceb8f713d'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205901010000-205912312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_205901010000-205912312300.nc' 'SHA256' '485b65f05f0f6b0d877496bc278bece47bff0e40f4ec6aa5f6c871969c4746a6'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206001010000-206012312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206001010000-206012312300.nc' 'SHA256' '2b0beb32689d53fdafd8acbbc8970796ede11dc2a501bc6c07ea1b880edef5f2'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206101010000-206112312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206101010000-206112312300.nc' 'SHA256' 'a5920209f13b7fc22c0c0725b93f35c19e8421ff019e3082c9df53f4ebf477ae'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206201010000-206212312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206201010000-206212312300.nc' 'SHA256' '666ec4560fb3e632a59c1de0ed4f2d259908aa9025d26872d1ccd48c4721886d'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206301010000-206312312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206301010000-206312312300.nc' 'SHA256' '46d4d0bf27aaf700f9d74c47f56f1ea0d39f34e22fddd2cebe2aa85cf29e1ea4'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206401010000-206412312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206401010000-206412312300.nc' 'SHA256' 'af269bc1d849655d49b39e51fa0f9f6a70a37b703b905a5e60a68b52e2fe7c53'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206501010000-206512312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206501010000-206512312300.nc' 'SHA256' 'be94702ffe6f59a3a7f66f03413c90ce0dc7e97c101fa8a6efd38557e94e991f'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206601010000-206612312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206601010000-206612312300.nc' 'SHA256' 'fd235820499a6e619706e4a1f173e0d14d88883bd74b098df46d5c0dc6a08bf3'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206701010000-206712312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206701010000-206712312300.nc' 'SHA256' 'a84e6b200dad12f0fe6de7890241f133cff6066c907a3678db5bf7e281def0d3'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206801010000-206812312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206801010000-206812312300.nc' 'SHA256' '03f649853571ca03aee690085bea7088e3eeb6b1224e0a3e5c7f203c81c5ef3b'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206901010000-206912312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_206901010000-206912312300.nc' 'SHA256' '0251ac5196675510befc0ca6e9d53ca28c55c13304d9c0ad6fdd37cd3db1e910'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207001010000-207012312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207001010000-207012312300.nc' 'SHA256' '01a18edafdd7681bf388e79885fd1b7924ff938d8d5cb7b7ebce1367e2010d46'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207101010000-207112312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207101010000-207112312300.nc' 'SHA256' '5195edec995f6e86f7a9903ba380432221edc7bb3d268dcdfac7d6f2d62961d9'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207201010000-207212312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207201010000-207212312300.nc' 'SHA256' '2fe12ca195d4a461644f0d60130715b1d13a9579d127e24899cb5de927342163'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207301010000-207312312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207301010000-207312312300.nc' 'SHA256' 'd56f34495928c81f5ba9696e7f6494761c9c6552a1a1c8eb1f0598b78fc2e848'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207401010000-207412312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207401010000-207412312300.nc' 'SHA256' 'e76a9ef518d8fbe09475b6f49f15729da8d6415c1680b370f534ae1c6528c2cd'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207501010000-207512312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207501010000-207512312300.nc' 'SHA256' '9e1e558ee4603d3019d704fb6ef5510e1c923e0dc1f9b556fdbed1c7eb2da5ef'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207601010000-207612312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207601010000-207612312300.nc' 'SHA256' '80071ee237da9cc71fe456cc827a0c3be45861043f1729025757393577630bab'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207701010000-207712312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207701010000-207712312300.nc' 'SHA256' '24e5409a9eb96bf12614437c5b73b8278facf17c4f3e431247862159dd644df4'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207801010000-207812312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207801010000-207812312300.nc' 'SHA256' 'fb1c547bfbaccc65ca044439dc8e80a5b9c2a6df4c3db4e96590c5c05e5c1abe'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207901010000-207912312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_207901010000-207912312300.nc' 'SHA256' '00d029da0bd79c357d267ad83bca9bc21ea94c3f2d1f56d4e7904b49e0763199'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208001010000-208012312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208001010000-208012312300.nc' 'SHA256' 'f9cf28e9cded8165353c35fb61e64ce70951c6315cee0701a941e85f2182b905'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208101010000-208112312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208101010000-208112312300.nc' 'SHA256' '71e60bcbaefb614e6f8b2ab4f5f8bf2861387e9c52faffe48b49c1fc6fd64f0b'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208201010000-208212312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208201010000-208212312300.nc' 'SHA256' '2ed8d771e7fa094450dc4a07c626eccf2fb1e264bc81a1e9062a2ae414286b06'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208301010000-208312312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208301010000-208312312300.nc' 'SHA256' 'e77756e6b62663bebbc5fe8e7dd4a651e41eba8143e2eec83461baf910ae78e0'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208401010000-208412312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208401010000-208412312300.nc' 'SHA256' '7f29479a0b4aedaa9fbd02fe800f6ffc0f6c94cc450e1df4b0943912262f06aa'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208501010000-208512312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208501010000-208512312300.nc' 'SHA256' '89f331af9b01b13b159da2b43a4920f4c749773ae91832756209c60b76f38f9b'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208601010000-208612312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208601010000-208612312300.nc' 'SHA256' '976efbc88aa764b29f25c7ec37f793ef3b06c9fe59f26521ff797ec36d80e321'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208701010000-208712312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208701010000-208712312300.nc' 'SHA256' '881203d753f9369c81632bdf6e56a6e53b8bf1173725bb3f504dbcd27aafbd41'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208801010000-208812312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208801010000-208812312300.nc' 'SHA256' '931ae832d146be3ce4d262a8b539c9d84b310b8cd1c2c499bcd2190fb7004081'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208901010000-208912312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_208901010000-208912312300.nc' 'SHA256' '7ce7fdf358d5e37cf30e9f11ec23dcc244adc1e8eb249dfe69ad0e453bec34e3'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209001010000-209012312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209001010000-209012312300.nc' 'SHA256' 'afd4d28c6df3eed19610901e80427383065e6284fb0cbcd429711bbabd48baf8'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209101010000-209112312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209101010000-209112312300.nc' 'SHA256' '18f6485d9ff2ea6861cea9fed071fb601a6959ae66dec9b06ff87b9617b108ab'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209201010000-209212312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209201010000-209212312300.nc' 'SHA256' 'f4139a2de7d63cd3456b9aa7e483aa210e7dcca20c0bba8e6aac50508d45a4d9'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209301010000-209312312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209301010000-209312312300.nc' 'SHA256' '90844818e81ec0eda2325908b772a8c6812d13728b101f27b4aa3b0f87480cad'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209401010000-209412312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209401010000-209412312300.nc' 'SHA256' 'efed9bbee1a3f3cb0d5c5b7d77e1acca09079c699ea1dc8f4e87a69e496cbe39'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209501010000-209512312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209501010000-209512312300.nc' 'SHA256' '88b5ce5770d0786efea3137653dc312fc551c98bc31b7d827148698b0a33c5e9'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209601010000-209612312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209601010000-209612312300.nc' 'SHA256' 'df3f29d18512ed2e0ce6f100b699f94c521755aae698c41f29cd7902656227a3'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209701010000-209712312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209701010000-209712312300.nc' 'SHA256' '0137f50e41258842dd3e209d813f6b74e39796104f825aefd0d7988fdcf6c93e'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209801010000-209812312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209801010000-209812312300.nc' 'SHA256' 'e0b72b8ebf9a39736dbb10ca48016662b0eec2c46f0ce5b3270ba64148e4048e'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209901010000-209912312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_209901010000-209912312300.nc' 'SHA256' '0c94ffa4afb81fe243dd1eedbf088541f241605722091043880e22d3ceca6100'
'tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_210001010000-210012312300.nc' 'http://esgf1.dkrz.de/thredds/fileServer/cordex_l02/cordex/output/EUR-11/CLMcom-ETH/NCC-NorESM1-M/rcp85/r1i1p1/CLMcom-ETH-COSMO-crCLIM-v1-1/v1/1hr/tas/v20191217/tas_EUR-11_NCC-NorESM1-M_rcp85_r1i1p1_CLMcom-ETH-COSMO-crCLIM-v1-1_v1_1hr_210001010000-210012312300.nc' 'SHA256' 'c23367f8ac6ce0f9e7571ec6cb7bc43adcc66996ce025a04ecfe39324d9d615b'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 95 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
